from __future__ import annotations

from datetime import datetime, timezone
import json
import subprocess


BASHWS_ID_URL = "https://bash.ws/id"
BASHWS_RESULT_URL = "https://bash.ws/dnsleak/test/{leak_id}?json"


def _now_iso():
    return datetime.now(timezone.utc).isoformat()


def parse_bashws_results(payload):
    """
    Convert bash.ws DNS-leak output into a conservative health signal.

    A resolver ASN differing from the observed exit ASN is reported as
    "potential_leak", not as a definitive leak: privacy-oriented third-party
    DNS providers can legitimately use a different ASN.
    """
    if not isinstance(payload, list):
        raise ValueError("DNS leak service returned an unexpected response.")

    exit_row = next(
        (row for row in payload if isinstance(row, dict) and row.get("type") == "ip"),
        None,
    )
    dns_rows = [
        row for row in payload
        if isinstance(row, dict) and row.get("type") == "dns"
    ]
    conclusion_row = next(
        (
            row for row in payload
            if isinstance(row, dict) and row.get("type") == "conclusion"
        ),
        None,
    )

    exit_asn = (exit_row or {}).get("asn") or None
    exit_ip = (exit_row or {}).get("ip") or None

    resolvers = []
    for row in dns_rows:
        resolvers.append({
            "ip": row.get("ip"),
            "asn": row.get("asn") or None,
            "country": row.get("country_name") or None,
        })

    if not resolvers:
        state = "unavailable"
        detail = "No DNS resolver was observed by the external test."
    else:
        resolver_asns = {r["asn"] for r in resolvers if r.get("asn")}
        if exit_asn and resolver_asns and all(a == exit_asn for a in resolver_asns):
            state = "no_obvious_leak"
            detail = "Observed DNS resolver ASN matches the VPN exit ASN."
        elif exit_asn and resolver_asns:
            state = "potential_leak"
            detail = (
                "One or more observed DNS resolver ASNs differ from the VPN "
                "exit ASN. This can indicate a DNS leak, but third-party DNS "
                "providers can also produce this result legitimately."
            )
        else:
            state = "observed"
            detail = "DNS resolvers were observed, but ASN comparison was incomplete."

    return {
        "state": state,
        "detail": detail,
        "exit_ip": exit_ip,
        "exit_asn": exit_asn,
        "resolvers": resolvers,
        "service_conclusion": (
            (conclusion_row or {}).get("ip")
            if conclusion_row
            else None
        ),
        "checked_at": _now_iso(),
    }


def run_dns_leak_probe(runtime, profile, iface, tunnel_ip, query_count=6):
    """
    Run a DNS-leak visibility probe pinned to an outbound VPN tunnel.

    This measures DNS behavior generated by VPN Router itself while pinned to
    the tunnel. It does not rewrite DNS and cannot guarantee that an individual
    WireGuard client is using the same resolver configuration.
    """
    runtime.ensure_probe_route(profile, iface, tunnel_ip)

    id_result = subprocess.run(
        [
            "curl", "--silent", "--show-error", "--fail",
            "--max-time", "6",
            "--interface", tunnel_ip,
            BASHWS_ID_URL,
        ],
        text=True,
        capture_output=True,
        timeout=8,
        check=False,
    )
    leak_id = id_result.stdout.strip()
    if id_result.returncode != 0 or not leak_id or len(leak_id) > 64:
        raise RuntimeError(
            "Could not initialise the external DNS leak test through the VPN."
        )

    successful_queries = 0
    for index in range(1, max(1, int(query_count)) + 1):
        hostname = f"{index}.{leak_id}.bash.ws"
        result = subprocess.run(
            [
                "ping",
                "-4",
                "-I", iface,
                "-c", "1",
                "-W", "2",
                hostname,
            ],
            text=True,
            capture_output=True,
            timeout=4,
            check=False,
        )
        # ICMP reachability is irrelevant here; the DNS lookup is the signal.
        # Count the trigger unless name resolution itself clearly failed.
        combined = (result.stdout or "") + "\n" + (result.stderr or "")
        lowered = combined.lower()
        if (
            "unknown host" not in lowered
            and "name or service not known" not in lowered
            and "temporary failure in name resolution" not in lowered
        ):
            successful_queries += 1

    if successful_queries == 0:
        raise RuntimeError(
            "DNS queries could not be generated through the VPN tunnel."
        )

    result = subprocess.run(
        [
            "curl", "--silent", "--show-error", "--fail",
            "--max-time", "7",
            "--interface", tunnel_ip,
            BASHWS_RESULT_URL.format(leak_id=leak_id),
        ],
        text=True,
        capture_output=True,
        timeout=9,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError("Could not retrieve DNS leak test results.")

    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError("DNS leak service returned invalid JSON.") from exc

    parsed = parse_bashws_results(payload)
    parsed["queries_attempted"] = max(1, int(query_count))
    parsed["queries_completed"] = successful_queries
    return parsed
