from __future__ import annotations

from datetime import datetime, timezone
import json
import subprocess


BASHWS_ID_URL = "https://bash.ws/id"
BASHWS_RESULT_URL = "https://bash.ws/dnsleak/test/{leak_id}?json"


def _now_iso():
    return datetime.now(timezone.utc).isoformat()


def parse_bashws_results(payload):
    """
    Convert bash.ws DNS-leak output into a conservative health signal.

    A resolver ASN differing from the observed exit ASN is reported as
    "potential_leak", not as a definitive leak: privacy-oriented third-party
    DNS providers can legitimately use a different ASN.
    """
    if not isinstance(payload, list):
        raise ValueError("DNS leak service returned an unexpected response.")

    exit_row = next(
        (row for row in payload if isinstance(row, dict) and row.get("type") == "ip"),
        None,
    )
    dns_rows = [
        row for row in payload
        if isinstance(row, dict) and row.get("type") == "dns"
    ]
    conclusion_row = next(
        (
            row for row in payload
            if isinstance(row, dict) and row.get("type") == "conclusion"
        ),
        None,
    )

    exit_asn = (exit_row or {}).get("asn") or None
    exit_ip = (exit_row or {}).get("ip") or None

    resolvers = []
    for row in dns_rows:
        resolvers.append({
            "ip": row.get("ip"),
            "asn": row.get("asn") or None,
            "country": row.get("country_name") or None,
        })

    if not resolvers:
        state = "unavailable"
        detail = "No DNS resolver was observed by the external test."
    else:
        resolver_asns = {r["asn"] for r in resolvers if r.get("asn")}
        if exit_asn and resolver_asns and all(a == exit_asn for a in resolver_asns):
            state = "no_obvious_leak"
            detail = "Observed DNS resolver ASN matches the VPN exit ASN."
        elif exit_asn and resolver_asns:
            state = "potential_leak"
            detail = (
                "One or more observed DNS resolver ASNs differ from the VPN "
                "exit ASN. This can indicate a DNS leak, but third-party DNS "
                "providers can also produce this result legitimately."
            )
        else:
            state = "observed"
            detail = "DNS resolvers were observed, but ASN comparison was incomplete."

    return {
        "state": state,
        "detail": detail,
        "exit_ip": exit_ip,
        "exit_asn": exit_asn,
        "resolvers": resolvers,
        "service_conclusion": (
            (conclusion_row or {}).get("ip")
            if conclusion_row
            else None
        ),
        "checked_at": _now_iso(),
    }


def run_dns_leak_probe(runtime, profile, iface, tunnel_ip, query_count=6):
    """
    Run a DNS-leak visibility probe pinned to an outbound VPN tunnel.

    This measures DNS behavior generated by VPN Router itself while pinned to
    the tunnel. It does not rewrite DNS and cannot guarantee that an individual
    WireGuard client is using the same resolver configuration.

    This generic probe intentionally has no resolver-specific routing logic.
    Forced/custom resolver validation is handled separately by
    run_explicit_resolver_probe().
    """
    runtime.ensure_probe_route(profile, iface, tunnel_ip)

    id_result = subprocess.run(
        [
            "curl", "--silent", "--show-error", "--fail",
            "--max-time", "6",
            "--interface", tunnel_ip,
            BASHWS_ID_URL,
        ],
        text=True,
        capture_output=True,
        timeout=8,
        check=False,
    )

    leak_id = id_result.stdout.strip()
    if id_result.returncode != 0 or not leak_id or len(leak_id) > 64:
        raise RuntimeError(
            "Could not initialise the external DNS leak test through the VPN."
        )

    queries_attempted = max(1, int(query_count))

    for index in range(1, queries_attempted + 1):
        hostname = f"{index}.{leak_id}.bash.ws"
        try:
            subprocess.run(
                [
                    "ping",
                    "-4",
                    "-I", iface,
                    "-c", "1",
                    "-W", "2",
                    hostname,
                ],
                text=True,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=4,
                check=False,
            )
        except subprocess.TimeoutExpired:
            # DNS resolution is the signal. bash.ws hostnames do not need to
            # reply to ICMP, matching the upstream dnsleaktest behavior.
            pass

    result = subprocess.run(
        [
            "curl", "--silent", "--show-error", "--fail",
            "--max-time", "7",
            "--interface", tunnel_ip,
            BASHWS_RESULT_URL.format(leak_id=leak_id),
        ],
        text=True,
        capture_output=True,
        timeout=9,
        check=False,
    )

    if result.returncode != 0:
        raise RuntimeError("Could not retrieve DNS leak test results.")

    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError("DNS leak service returned invalid JSON.") from exc

    parsed = parse_bashws_results(payload)
    parsed["queries_attempted"] = queries_attempted
    parsed["queries_completed"] = queries_attempted
    return parsed


def run_explicit_resolver_probe(
    runtime,
    profile,
    iface,
    tunnel_ip,
    resolver_ip,
    routing_table_id,
    query_count=6,
):
    """
    Validate a configured classic-DNS resolver through a specific VPN tunnel.

    WG-Easy client DNS is policy-routed through the routing group's fwmark/table.
    Local probe traffic does not traverse nftables prerouting, so this function
    temporarily installs a narrow source+destination policy rule that mirrors
    the routing group's table for the configured resolver.
    """
    runtime.ensure_probe_route(profile, iface, tunnel_ip)

    probe_priority = 18000 + int(profile.id)

    # Clear a stale probe rule from an interrupted prior run.
    subprocess.run(
        [
            "ip", "-4", "rule", "del",
            "priority", str(probe_priority),
        ],
        text=True,
        capture_output=True,
        timeout=3,
        check=False,
    )

    rule_result = subprocess.run(
        [
            "ip", "-4", "rule", "add",
            "priority", str(probe_priority),
            "from", f"{tunnel_ip}/32",
            "to", f"{resolver_ip}/32",
            "lookup", str(int(routing_table_id)),
        ],
        text=True,
        capture_output=True,
        timeout=3,
        check=False,
    )
    if rule_result.returncode != 0:
        detail = (rule_result.stderr or rule_result.stdout or "").strip()
        raise RuntimeError(
            "Could not prepare the routing-group path for the DNS probe"
            + (f": {detail}" if detail else ".")
        )

    try:
        id_result = subprocess.run(
            [
                "curl", "--silent", "--show-error", "--fail",
                "--max-time", "6",
                "--interface", tunnel_ip,
                BASHWS_ID_URL,
            ],
            text=True,
            capture_output=True,
            timeout=8,
            check=False,
        )

        leak_id = id_result.stdout.strip()
        if id_result.returncode != 0 or not leak_id or len(leak_id) > 64:
            raise RuntimeError(
                "Could not initialise the external DNS leak test through the VPN."
            )

        queries_attempted = max(1, int(query_count))

        for index in range(1, queries_attempted + 1):
            hostname = f"{index}.{leak_id}.bash.ws"
            result = subprocess.run(
                [
                    "dig",
                    "-4",
                    "-b", tunnel_ip,
                    f"@{resolver_ip}",
                    "+time=3",
                    "+tries=1",
                    "+short",
                    hostname,
                ],
                text=True,
                capture_output=True,
                timeout=5,
                check=False,
            )

            if result.returncode != 0:
                detail = (result.stderr or result.stdout or "").strip()
                raise RuntimeError(
                    f"Configured DNS resolver {resolver_ip} is not reachable "
                    "through this VPN tunnel"
                    + (f": {detail}" if detail else ".")
                )

        result = subprocess.run(
            [
                "curl", "--silent", "--show-error", "--fail",
                "--max-time", "7",
                "--interface", tunnel_ip,
                BASHWS_RESULT_URL.format(leak_id=leak_id),
            ],
            text=True,
            capture_output=True,
            timeout=9,
            check=False,
        )

        if result.returncode != 0:
            raise RuntimeError("Could not retrieve DNS leak test results.")

        try:
            payload = json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise RuntimeError("DNS leak service returned invalid JSON.") from exc

        parsed = parse_bashws_results(payload)
        parsed["queries_attempted"] = queries_attempted
        parsed["queries_completed"] = queries_attempted
        parsed["configured_resolver"] = resolver_ip
        return parsed

    finally:
        subprocess.run(
            [
                "ip", "-4", "rule", "del",
                "priority", str(probe_priority),
            ],
            text=True,
            capture_output=True,
            timeout=3,
            check=False,
        )


